"""Ablation variants for confirmatory and exploratory evaluation phases.

Maps variant names to fixed VCLManifest instances — version-controlled so
any change to a variant definition is visible in git diff and requires a
deviation log entry if it has analytic consequence (§3.6.7).

CONFIRMATORY_VARIANTS: 8 pre-registered variants for the 16k-run ablation.
EXPLORATORY_VARIANTS:  7 variants for OTEL Demo exploratory runs (OSF §3.2);
                       excluded from confirmatory analysis by evaluation_phase.
"""

from __future__ import annotations

from .config import VCLManifest

# All variants share ingest_mode="recorded" (primary evaluation protocol).
# router=True is the VCLManifest default; only HELIOS-noRouter overrides it.
CONFIRMATORY_VARIANTS: dict[str, VCLManifest] = {
    "HELIOS-Full": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noLLM": VCLManifest.from_flags(
        l2c_llm=False,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=False,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noGraph": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=False,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=False,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-D": VCLManifest.from_flags(
        l2c_llm=False,
        p4_cognitive=True,
        mahc=False,
        cbr=False,
        l2b_graph=False,
        acp=False,
        reconcile=False,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=False,
        lpipe=False,
        router=False,
        ingest_mode="recorded",
    ),
    "HELIOS-G": VCLManifest.from_flags(
        l2c_llm=False,
        p4_cognitive=True,
        mahc=False,
        cbr=False,
        l2b_graph=True,
        acp=False,
        reconcile=False,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=False,
        gpipe=True,
        lpipe=False,
        router=False,
        ingest_mode="recorded",
    ),
    "HELIOS-noConsensus": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=False,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noRouter": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=False,
        ingest_mode="recorded",
    ),
    "HELIOS-noStructural": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=False,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
}


EXPLORATORY_VARIANTS: dict[str, VCLManifest] = {
    # Each variant is HELIOS-Full with exactly one flag changed, except
    # HELIOS-noLLM-noGraph (compound) and HELIOS-live (ingest_mode change).
    "HELIOS-noP4": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=False,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noMAHC": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=False,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noCBR": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=False,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noACP": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=False,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-noReconcile": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=False,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="recorded",
    ),
    "HELIOS-live": VCLManifest.from_flags(
        l2c_llm=True,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=True,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=True,
        lpipe=True,
        router=True,
        ingest_mode="live",
    ),
    "HELIOS-noLLM-noGraph": VCLManifest.from_flags(
        l2c_llm=False,
        p4_cognitive=True,
        mahc=True,
        cbr=True,
        l2b_graph=False,
        acp=True,
        reconcile=True,
        ueg_c_structural=True,
        dpipe=True,
        dpipe_propagation=True,
        gpipe=False,
        lpipe=False,
        router=True,
        ingest_mode="recorded",
    ),
}


def get_variant(name: str) -> VCLManifest:
    """Resolve a variant name to its VCLManifest (confirmatory first, then exploratory)."""
    if name in CONFIRMATORY_VARIANTS:
        return CONFIRMATORY_VARIANTS[name]
    if name in EXPLORATORY_VARIANTS:
        return EXPLORATORY_VARIANTS[name]
    all_names = sorted({*CONFIRMATORY_VARIANTS, *EXPLORATORY_VARIANTS})
    raise ValueError(f"Unknown variant: {name!r}. Available: {all_names}")
